export const posts = [
  {
    slug: 'nclex-april-2026-test-plan-changes',
    title: 'NCLEX Test Plan Changes April 2026: What Every Nursing Student Needs to Know',
    metaTitle: 'NCLEX April 2026 Test Plan Changes: Complete Guide for Nursing Students',
    metaDescription: 'The NCLEX test plan changes on April 1, 2026. Learn what\'s new, how categories are shifting, and how Next Generation NCLEX (NGN) affects your prep.',
    keyword: 'NCLEX April 2026 Test Plan Changes',
    date: '2026-03-09', readTime: '8 min read', category: 'Exam Prep',
    excerpt: 'The NCSBN officially updated the NCLEX test plan effective April 1, 2026. New content categories, revised passing standards, and enhanced NGN clinical judgment requirements — here\'s exactly what changed and how to prepare.',
  },
  {
    slug: 'next-generation-nclex-ngn-question-types',
    title: 'Next Generation NCLEX (NGN) Question Types: Complete Guide with Examples',
    metaTitle: 'NGN Question Types Explained: Bow-Tie, Matrix, Extended Response & More',
    metaDescription: 'Master every Next Generation NCLEX question type — bow-tie, extended multiple response, matrix/grid, trend, and cloze. Includes examples and strategies for each.',
    keyword: 'Next Generation NCLEX NGN Question Types',
    date: '2026-03-09', readTime: '9 min read', category: 'Question Strategy',
    excerpt: 'The Next Generation NCLEX introduced new question formats that test clinical judgment differently than traditional multiple choice. Here\'s a complete breakdown of every NGN question type with examples and how to approach each one.',
  },
  {
    slug: 'best-nclex-study-strategies',
    title: 'Best NCLEX Study Strategies: 7 Proven Methods to Pass on Your First Attempt',
    metaTitle: 'Best NCLEX Study Strategies: 7 Proven Methods to Pass First Try',
    metaDescription: 'Discover the best NCLEX study strategies used by nurses who passed on their first attempt. Includes an 8-week schedule, practice questions, and expert tips.',
    keyword: 'Best NCLEX Study Strategies',
    date: '2026-03-04', readTime: '9 min read', category: 'Study Tips',
    excerpt: 'The NCLEX has a national pass rate of around 82%. The difference between passing and failing rarely comes down to intelligence — it comes down to how you study.',
  },
  {
    slug: 'nclex-pharmacology-tips',
    title: 'NCLEX Pharmacology Tips: How to Master Medications Without Memorizing Everything',
    metaTitle: 'NCLEX Pharmacology Tips: Master Medications for the NCLEX Exam',
    metaDescription: 'Learn the top NCLEX pharmacology tips that nursing students use to master medications without memorizing every drug.',
    keyword: 'NCLEX Pharmacology Tips',
    date: '2026-03-04', readTime: '8 min read', category: 'Pharmacology',
    excerpt: 'Pharmacology makes up 12–18% of the NCLEX. You cannot memorize every drug — but you can master the patterns that cover 80% of what the exam actually tests.',
  },
  {
    slug: 'how-to-pass-nclex-first-try',
    title: 'How to Pass the NCLEX First Try: The Complete 2026 Guide',
    metaTitle: 'How to Pass the NCLEX First Try: Complete 2026 Guide',
    metaDescription: 'Want to know how to pass the NCLEX first try? This complete guide covers study plans, question strategies, mindset, and what to do the week before your exam.',
    keyword: 'How to Pass NCLEX First Try',
    date: '2026-03-04', readTime: '10 min read', category: 'Exam Prep',
    excerpt: 'Passing the NCLEX on your first attempt is absolutely achievable — but it requires more than just studying hard. Here is exactly what to do.',
  },
  {
    slug: 'nclex-sata-questions-strategies',
    title: 'NCLEX SATA Questions: 5 Strategies to Stop Getting Them Wrong',
    metaTitle: 'NCLEX SATA Questions: 5 Strategies to Stop Getting Them Wrong',
    metaDescription: 'Select-All-That-Apply questions are the most failed question type on the NCLEX. These 5 SATA strategies will change how you approach every one of them.',
    keyword: 'NCLEX SATA Questions',
    date: '2026-03-04', readTime: '7 min read', category: 'Question Strategy',
    excerpt: 'SATA questions are the most feared question type on the NCLEX — and for good reason. Most students approach them wrong. Here is the fix.',
  },
  {
    slug: 'nclex-priority-questions-tips',
    title: 'NCLEX Priority Questions: How to Answer "Which Patient Do You See First"',
    metaTitle: 'NCLEX Priority Questions: How to Answer Which Patient First',
    metaDescription: 'NCLEX priority questions trip up thousands of nursing students. Learn the exact frameworks — ABC, Maslow, Stable vs Unstable — that make these questions predictable.',
    keyword: 'NCLEX Priority Questions',
    date: '2026-03-04', readTime: '8 min read', category: 'Question Strategy',
    excerpt: 'Priority questions appear on nearly every NCLEX exam. Once you know the three frameworks nurses use, these become the easiest questions on the test.',
  },
  {
    slug: 'nclex-lab-values-guide',
    title: 'NCLEX Lab Values You Must Memorize: The Complete Guide',
    metaTitle: 'NCLEX Lab Values You Must Memorize (Complete Cheat Sheet)',
    metaDescription: 'Master NCLEX lab values with this complete guide. Normal ranges, critical values, and what each lab result means for nursing interventions.',
    keyword: 'NCLEX Lab Values',
    date: '2026-03-05', readTime: '8 min read', category: 'Study Tips',
    excerpt: 'Lab values questions appear on every NCLEX exam. This complete guide covers every critical lab value, normal range, and the nursing action the NCLEX expects.',
  },
  {
    slug: 'nclex-2-week-study-plan',
    title: 'How to Study for the NCLEX in 2 Weeks: A Realistic Day-by-Day Plan',
    metaTitle: 'How to Study for the NCLEX in 2 Weeks (Realistic 14-Day Plan)',
    metaDescription: 'Need to study for the NCLEX in 2 weeks? This realistic day-by-day plan tells you exactly what to study each day to maximize your chances of passing.',
    keyword: 'How to Study for NCLEX in 2 Weeks',
    date: '2026-03-05', readTime: '9 min read', category: 'Study Plans',
    excerpt: 'Two weeks is tight but it is enough time to pass the NCLEX if you are strategic. Here is a day-by-day plan that prioritizes the highest-yield content.',
  },
  {
    slug: 'fail-nclex-what-happens',
    title: 'What Happens If You Fail the NCLEX? Your Complete Retake Guide',
    metaTitle: 'What Happens If You Fail the NCLEX? Complete Retake Guide (2026)',
    metaDescription: 'Failed the NCLEX? Here is exactly what happens next — retake rules, wait periods, what to study differently, and how thousands of nurses passed on their second attempt.',
    keyword: 'What Happens If You Fail NCLEX',
    date: '2026-03-05', readTime: '8 min read', category: 'Exam Prep',
    excerpt: 'Failing the NCLEX is more common than most nursing students realize — and it is not the end. Here is exactly what happens next and how to come back stronger.',
  },
  {
    slug: 'nclex-test-day-tips',
    title: 'NCLEX Test Day Tips: What Every Nursing Student Must Know Before Walking In',
    metaTitle: 'NCLEX Test Day Tips: What Every Nursing Student Must Know',
    metaDescription: 'These NCLEX test day tips cover everything from what to bring, how to manage time, what to do when you hit hard questions, and how to stay mentally sharp.',
    keyword: 'NCLEX Test Day Tips',
    date: '2026-03-05', readTime: '7 min read', category: 'Exam Prep',
    excerpt: 'What you do the 24 hours before your NCLEX matters almost as much as what you studied. Here is exactly what to do and what to avoid on test day.',
  },
  {
    slug: 'nclex-study-schedule',
    title: 'NCLEX Study Schedule: The 8-Week Plan That Works',
    metaTitle: 'NCLEX Study Schedule: 8-Week Plan That Actually Works',
    metaDescription: 'Follow this proven 8-week NCLEX study schedule to build strong knowledge, practice questions daily, and walk into the exam fully prepared.',
    keyword: 'NCLEX Study Schedule',
    date: '2026-03-05', readTime: '9 min read', category: 'Study Plans',
    excerpt: 'An 8-week study schedule gives you enough time to cover all content areas, practice thousands of questions, and review weak areas before exam day.',
  },
];

export function getPost(slug) {
  return posts.find(p => p.slug === slug) || null;
}

export function getAllSlugs() {
  return posts.map(p => p.slug);
}
